package:
  name: power1d
  version: 0.1.4


source:
  path: ../


build:
  script: python setup.py install
  number: 3

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib
    - nose
    - future
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - future

# test:
#   imports:
#    - power1d

about:
  summary: Numerical Power Estimates for One-Dimensional Continua
  home: https://spm1d.org/power1d
  license: GPL