name: push-pypi
# name: push-test-pypi

on:
  push:
    branches: [ master ]


jobs:
  publish-test-pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Build
      run: python -m build .
    - name: Test with pytest
      run: |
        python -m pip install -U pytest pytest-explicit numpy scipy matplotlib
        export PYTHONPATH=src
        python -m pytest tests/
        
    - name: Publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true

